### ISSUE TITLE
Add [ConferenceName Year] to Each Paper in the colomn of `Links` or `链接`

### ISSUE THREAD

**Issue by chg0901** [mini-sora/minisora#101]
For example：

| <h3>Diffusion Model</h3> |  |
| :------------- | :------------- |
| **论文**  | **链接** |
| 1) [ICCV 23] **StableVideo**: Text-driven Consistency-aware Diffusion Video Editing | [Paper](https://arxiv.org/abs/2308.09592), [Github](https://github.com/rese1f/StableVideo), [Project](https://rese1f.github.io/StableVideo/) |
| 2)  [CVPR 24] **MovieChat**: From Dense Token to Sparse Memory for Long Video Understanding | [Paper](https://arxiv.org/abs/2307.16449), [Github](https://github.com/rese1f/MovieChat), [Project](https://rese1f.github.io/MovieChat/) |
| 3)  **DDPM**: Denoising Diffusion Probabilistic Models | [Paper](https://arxiv.org/abs/2006.11239), [Github](https://github.com/hojonathanho/diffusion) |

This table in the above could be changed as the following:

| <h3>Diffusion Model</h3> |  |
| :------------- | :------------- |
| **论文**  | **链接** |
| 1) **StableVideo**: Text-driven Consistency-aware Diffusion Video Editing | [**ICCV 23 Paper**](https://arxiv.org/abs/2308.09592), [Github](https://github.com/rese1f/StableVideo), [Project](https://rese1f.github.io/StableVideo/) |
| 2)  **MovieChat**: From Dense Token to Sparse Memory for Long Video Understanding |  [**CVPR 24 Paper**](https://arxiv.org/abs/2307.16449), [Github](https://github.com/rese1f/MovieChat), [Project](https://rese1f.github.io/MovieChat/) |
| 3)  **DDPM**: Denoising Diffusion Probabilistic Models |  [**NeurIPS 20 Paper**](https://arxiv.org/abs/2006.11239), [Github](https://github.com/hojonathanho/diffusion) |

**Comment by JunyaoHu** [comment]
If the paper is already a conference paper rather than arxiv, should we replace the link with the conference version?

like 

StableVideo: https://openaccess.thecvf.com/content/ICCV2023/html/Chai_StableVideo_Text-driven_Consistency-aware_Diffusion_Video_Editing_ICCV_2023_paper.html

DDPM: https://proceedings.neurips.cc//paper_files/paper/2020/hash/4c5bcfec8584af0d967f1ab10179ca4b-Abstract.html

**Comment by chg0901** [comment]
I recommend keeping the arXiv link(https://arxiv.org/abs/2308.09592) and the abbreviated conference name (ICCV 23 Paper). 

ArXiv papers often contain more detailed information and supplemental resources compared to the conference paper version. Additionally, arXiv papers are accessible to anyone, making them a valuable resource for reference and further exploration
