### ISSUE TITLE
Update an issue template which is more appropriate for this repo

### ISSUE THREAD

**Issue by JunyaoHu** [mini-sora/minisora#119]
**Is your feature request related to a problem? Please describe.**
The current template is more inclined to the template of the development project, and a template more suitable for the style of this project is needed.

**Describe the solution you'd like**
Type of issue may include:

1. Request to add / update the code repo, arxiv website, project website, blog, demo of a paper... 
2. Add / Fix features of this repo. 
3. Typographical / link / spelling issues...
4. Other discussions...

**Describe alternatives you've considered**
None.

**Additional context**
We can refer to openmmlab's template. And you can comment below to supplement your suggestions. I may finish this task tonight.

**Comment by seifer08ms** [comment]
The template from OpenMMLab is quite good. Furthermore, I'm also providing a document issue template that might be more suitable for minisora's needs. You can refer to it to see if it's appropriate:

--------------------------

# **Title**: [Update Type] - [Brief Description]

## **Update Type**:

 Add new paper/project/resource
 Update existing paper/project/resource information
 Remove outdated paper/project/resource
 Correct document formatting/link/spelling errors
 Other document updates

## **Detailed Description**:

**Content Name/Link**: [Provide the name or link of the content that needs to be updated]
**Current Status/Issue**: [Briefly describe the current status or problem with the content]
**Update Details**: [Describe in detail the updates you wish to make, including new information, modifications, or removal of outdated content]

## **Additional Information**:
**Reason for Update**: [Explain why the update is necessary and how it will benefit the community]
**Deadline (if any)**: [If there is a specific deadline for the update, please provide it]
