### ISSUE TITLE
Update PR template so its title has different prefix tags.

### ISSUE THREAD

**Issue by JunyaoHu** [mini-sora/minisora#120]
**Is your feature request related to a problem? Please describe.**
![f222d698d3847e42b610efc1f980ec3](https://github.com/mini-sora/minisora/assets/67564714/1cb09e7a-4517-49c8-89f0-e709e1063fd7)
The current PR submission title is not standardized, it is best to unify the title format to facilitate the subsequent review and retrieval process.

**Describe the solution you'd like**
Create multiple PR templates. User should select the appropriate template when submitting, and automatically fill in prefix labels.

**Describe alternatives you've considered**
None.

**Additional context**
We can refer to openmmlab's template. And you can comment below to supplement your suggestions. I may finish this task tonight.

**Comment by seifer08ms** [comment]
The template from OpenMMLab is quite good. However, I'd like to recommend the format I used in my previous PR. This format might be more suitable for our project's document updates, as it can help reviewers quickly understand the contributions submitted by the contributors (Review Notes). You can also check out my PR [#53 ](https://github.com/mini-sora/minisora/pull/53)

------------------------

## Pull Request Description

### Summary
This pull request adds information about the xx paper and xx  project to the README file. XXX is xxx video diffusion model for xxx task.

### Changes
- Added a section in the README with links to the XXX paper, GitHub repository, and project website.
- Ensured that the links are functional and the information is up-to-date.

### Review Notes
- Please review the added content for accuracy and formatting.
- Check that the links provided are correct and lead to the intended resources.
- **Please check if both the Chinese and English READMEs have been updated simultaneously.**

### Related Issues
- Closes #issue-number (if there's an associated issue)

### Additional Comments
- The addition of XXX to our README will provide valuable resources for users interested in efficient video generation.
