### ISSUE TITLE
[Update] - Move two new survey papers into  "最近更新", which should be located before '论文复现小组' 

### ISSUE THREAD

**Issue by seifer08ms** [mini-sora/minisora#159]
## **Detailed Description**

**Content Name/Link**: [State of the Art on Diffusion Models for Visual Computing](http://arxiv.org/abs/2310.07204)

**Current Status/Issue**: The document may not include the latest advancements in diffusion models for visual computing.

**Update Details**: The "State of the Art on Diffusion Models for Visual Computing" paper will be incorporated.

## Update

**I think we could add these two new papers into "最近更新" to extract more attention for our SoraSurvey Team.**

**What's more,  "最近更新"  should also be moved to a place near the top part of README.md. For example, before '论文复现小组'**

## **Additional Information**
**Reason for Update**:  This paper provides an intuitive starting point to explore video Diffusion model topic for researchers, artists, and practitioners alike.

**Comment by chg0901** [comment]
I think we could add these two new papers into "最近更新" to extract more attention for our SoraSurvey Team.

What's more,  "最近更新"  should also be moved to a place near the top part of README.md. For example, before '论文复现小组'
