### ISSUE TITLE
Linking to a wrong page.

### ISSUE THREAD

**Issue by fgvfgfg564** [mini-sora/minisora#236]
It looks like this link is pointing to the wrong page. It points to the paper 'VideoLDM: Align your Latents: High-Resolution Video Synthesis with Latent Diffusion Models'.

![image](https://github.com/mini-sora/minisora/assets/38156654/224fa78a-dc33-4511-ac8f-7f5816c6ac17)

**Comment by seifer08ms** [comment]
Thank you for pointing out the mistake.  We will correct it as soon as possible. Also, we would appreciate it if you could help us submit the correction if you have the time. 😊
