### ISSUE TITLE
[Update] translate the notes/README.md in English

### ISSUE THREAD

**Issue by chg0901** [mini-sora/minisora#244]
# Issue description
The current `notes/README.md` is in Chinese, please refer other pages to translate it in Chinese.

**Steps：**
1. cope `notes/README.md` as `notes/README_CN.md`
2. translate the notes/README.md in English
3. add Chinese (`[English](./README.md)  | 简体中文 `) and English links(`English | [简体中文](./README_CN.md)  `) to `notes/README_CN.md` and `notes/README.md`

## 详情
目前的`notes/README.md`是中文的，请参考其他页面翻译成中文。

 **步骤**： 
1. 将 `notes/README.md` 处理为 `notes/README_CN.md` 
3. 将notes/README.md翻译成英文 
4. 3. 在`notes/README_CN.md`中添加中文链接(`[English](./README.md) | 简体中文`)和英文链接(`English | [简体中文](./README_CN.md)`) `注释/README.md`

**Comment by songqiang321** [comment]
Hi, I have solved the issue. Please see #245.

**Comment by chg0901** [comment]
@songqiang321  you can check your PR link, with a `Close #244` in your PR description, you could mention it and the issue could be closed when your PR were merged
