### ISSUE TITLE
[Add] paper 'Taming Transformers for High-Resolution Image Synthesis' to 'Diffusion Transformer'

### ISSUE THREAD

**Issue by chg0901** [mini-sora/minisora#255]
Add paper '**Taming Transformers for High-Resolution Image Synthesis**' to '**Diffusion Transformer**'

**CVPR 21** paper: https://openaccess.thecvf.com/content/CVPR2021/papers/Esser_Taming_Transformers_for_High-Resolution_Image_Synthesis_CVPR_2021_paper.pdf

Github: https://github.com/CompVis/taming-transformers

Project: https://compvis.github.io/taming-transformers/

**Comment by seifer08ms** [comment]
The approach outlined in this article seems to diverge from the typical diffusion models and diffusion Transformers. It appears to be an architecture that integrates CNNs with Transformers. As it's not specifically geared towards video generation, categorizing it might be a bit tricky.

**Comment by chg0901** [comment]
> The approach outlined in this article seems to diverge from the typical diffusion models and diffusion Transformers. It appears to be an architecture that integrates CNNs with Transformers. As it's not specifically geared towards video generation, categorizing it might be a bit tricky.

right, the main structure is Unet or AE,

**Comment by chg0901** [comment]
Is there other good works that use CNN only without Transformer?

**Comment by chg0901** [comment]
This issue is solved by #345
