### ISSUE TITLE
[Update] - add papers related to `PIXART-Σ`

### ISSUE THREAD

**Issue by chg0901** [mini-sora/minisora#258]
## Description
add papers related to `PIXART-Σ`

**project**: https://pixart-alpha.github.io/PixArt-sigma-project/

**papers and links**

PixArt-Σ: Weak-to-Strong Training of Diffusion Transformer for 4K Text-to-Image Generation
https://arxiv.org/pdf/2403.04692.pdf

PIXART-α: FAST TRAINING OF DIFFUSION TRANSFORMER FOR PHOTOREALISTIC TEXT-TO-IMAGE SYNTHESIS
https://arxiv.org/pdf/2310.00426.pdf

PIXART-δ: FAST AND CONTROLLABLE  IMAGE GENERATION WITH LATENT CONSISTENCY MODEL
https://arxiv.org/pdf/2401.05252.pdf

**Comment by Nobody-ML** [comment]
see #318 and #319
