### ISSUE TITLE
 Is there a relationship between video encoding standards and video compression in video generation?

### ISSUE THREAD

**Issue by xiexiaoshinick** [mini-sora/minisora#274]
I have some questions regarding the relationship between video encoding standards and video compression in video generation. From my understanding, video encoding standards such as H.261, H.262, H.263, H.264, and H.265 are used to compress digital videos, reducing file size or lowering bandwidth requirements. However, I would like to delve deeper into how these encoding standards are related to video compression in the context of video generation.
![Snipaste_2024-03-11_15-05-38](https://github.com/mini-sora/minisora/assets/26023731/d0ecb83e-d381-45b2-88e9-72bc8c2abee1)
I would greatly appreciate more detailed information to gain a better understanding of the relationship between video encoding standards and video compression. This knowledge will help me grasp the technical intricacies involved in video generation and processing.

Thank you for your assistance!

**Comment by chg0901** [comment]
I will provide a brief answer to your question. Prior to the use of deep learning or AGI for video generation, researchers employed these methods for video compression. In fact, the design of some video compression modules also mimics these standards to a certain extent.

Could you please answer his question in details or in other aspects @fanqiNO1 ?

**Comment by fanqiNO1** [comment]
On the one hand, the video compression model takes the latest decoded frame as a reference when encoding and decoding current frame, and the architecture of the video compression model is similar to the Variational Auto-Encoder (VAE). Therefore, if we replace the entropy model and byte stream part with a generative model, such as DiT, then the process of video generation will occur in the latent space of the video compression encoder. At the same time, the whole model can be regarded as an autoregressive video generation model referenced only to the previous generated frame.

On the other hand, as another typical spatio-temporal consistent model, the video compression model includes spatio-temporal information without relying on 3D convolution or spatio-temporal patches, although this is not in line with the technique mentioned by Sora in the technical report.  But the method of combining spatio-temporal information to achieve the spatio-temporal consistency is still part of the learning process. Meanwhile, a video generation model based on the video compression model architecture may also be an alternative to Sora in low-computing-power scenarios.
