### ISSUE TITLE
不成熟想法：复现模拟一个小世界的可能性？

### ISSUE THREAD

**Issue by limoncc** [mini-sora/minisora#64]
1、选定一部动漫(例如侠盗罗宾汉)或者电视剧(例如南来北往)，复现表现的世界。用来验证技术路径。
2、第一有对应小说文本支撑，数据量足够，场景不多比较固定

**Comment by chg0901** [comment]
那么可以先从构造数据集来入手,

**Comment by chg0901** [comment]
感谢您对MiniSora的关注， 由于目前更多的是对有关论文的整理和有关论文代码的复现，我们决定关闭这个Issue， 感谢关注， 期待你可以在项目中提交有关的数据集和代码PR。
