### ISSUE TITLE
add the two paper reading sources about Latte to the README_EN.md

### ISSUE THREAD

**Issue by chg0901** [mini-sora/minisora#81]
please mention that, these two files about **Latte** in **notes folder** are written by Chinese.

Such as `xx.pdf in Chinese`

**Comment by JunyaoHu** [comment]
solved in https://github.com/mini-sora/minisora/pull/85

**Comment by JunyaoHu** [comment]
solved in https://github.com/mini-sora/minisora/pull/86, please check it

**Comment by chg0901** [comment]
Good works.
